#!/bin/sh
 
# Always use neovim
alias vim="nvim" vimdiff="nvim -d"
 
# Dotfiles repo control
alias dotfiles="git --git-dir=$HOME/.config/dotfiles.git/ --work-tree=$HOME"
 
# SSH shortcuts
alias \
  sshN="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
  scpN="scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
 
# Verbosity and interactivity settings
alias                \
  cp="cp -iv"        \
  mv="mv -iv"        \
  rm="rm -v"         \
  ln="ln -v"         \
  mkd="mkdir -pv"    \
  rsync="rsync -hP"  \
 
# Colorize commands when possible
alias                                 \
  ls="ls -hG"                         \
  ll="ls -lAhG"                       \
  grep="grep --color=auto"            \
  ccat="highlight --out-format=ansi"  \
 
# Common commands abbreviation
alias                               \
  e="$EDITOR"                       \
  E="sudo $EDITOR"                  \
  s="sudo su -l"                    \
  q="exit"                          \
  ka="killall"                      \
  h="history -i -100000 | less +G"  \
  hs="history -i -100000 | grep"    \
 
# For `pass`
alias                                        \
  ppull="pass git pull"                      \
  ppush="pass git push"                      \
  psync="pass git fetch && pass git status"  \
  padd="pass insert -m"                      \
  pedit="pass edit"                          \
  pwg="pwgen -cns"                           \
  pw="pwgen -cns 20 1"                       \
  dw="diceware --no-caps -d -"               \

# Pbcopy without newline character
alias pbcopyn="tr -d '\n' | pbcopy"
