- name: Set up dotfiles
  hosts: all
  gather_facts: true

  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - git
          - tar
          - zsh
          - neovim
          - fzf
        update_cache: true
        cache_valid_time: 3600
      become: true

    - name: Create directory for zsh plugins
      ansible.builtin.file:
        path: ~/.local/share/zsh/plugins
        state: directory
        mode: "0755"

    - name: Install zsh plugins
      ansible.builtin.git:
        repo: "{{ item }}"
        dest: ~/.local/share/zsh/plugins/{{ item | basename | regex_replace('\\.git$', '') }}
        version: master
      loop:
        - https://github.com/Aloxaf/fzf-tab
        - https://github.com/jeffreytse/zsh-vi-mode
        - https://github.com/zdharma-continuum/fast-syntax-highlighting
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Install lf
      ansible.builtin.unarchive:
        src: https://github.com/gokcehan/lf/releases/latest/download/lf-linux-amd64.tar.gz
        dest: /usr/local/bin
        remote_src: true
        creates: /usr/local/bin/lf

    - name: Create directory for dotfiles repo
      ansible.builtin.file:
        path: ~/.local/share/dotfiles.git
        state: directory
        mode: "0755"

    - name: Clone dotfiles repo
      ansible.builtin.git:
        repo: https://github.com/denis-volin/dotfiles.git
        dest: ~/.local/share/dotfiles.git
        version: main
        bare: true
        single_branch: true
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Checkout dotfiles repo in home directory
      ansible.builtin.shell: # noqa: command-instead-of-module
        cmd: |
          git --git-dir="$HOME/.local/share/dotfiles.git" --work-tree="$HOME" checkout -f
          git --git-dir="$HOME/.local/share/dotfiles.git" --work-tree="$HOME" rm --cached --ignore-unmatch README.md LICENSE setup.sh
          rm -f "$HOME/README.md" "$HOME/LICENSE" "$HOME/setup.sh"
        creates: ~/.zshenv

    - name: Change shell to zsh
      ansible.builtin.user:
        name: "{{ ansible_facts['user_id'] }}"
        shell: /usr/bin/zsh
      become: true
